---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeweatherservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: codeweatherservice
    spec:
      containers:
      - name: codeweatherservice
        image: sindiapc/codeweatherservice:Dev3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: codeweatherservice
---
apiVersion: v1
kind: Service
metadata:
  name: codeweatherservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: codeweatherservice
