name: Print Environment Value  
on:  
  workflow_dispatch:  
    inputs:  
      environment:  
        type: choice  
        description: 'Which environment will be deployed?'  
        required: true  
        options:  
          - dev  
          - uat  
          - prod 
  
jobs:  
  print:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v2  
  
      - name: Echo a Message  
        run: echo "This is a sample message from GitHub Actions"  
  
      - name: Print Environment Variable  
        run: echo "The value of MY_VARIABLE is ${{ vars.SINDIA_VARIABLE }}"  
        env:  
          MY_VARIABLE: ${{ vars.SINDIA_VARIABLE }}
